- name: Applying the New Relic monitoring stack
  shell: "kubectl apply -f {{ kubernetes_resources_directory }}/nri-monitoring/{{item}}"
  environment:
    KUBECONFIG: '{{ kubeconfig_path }}'
  loop:
  - nri-namespace.yaml
  - nri-kube-state-metrics.yaml
  - nri-kube-events.yaml
  - nri-infraestructure.yaml
  - nri-logging.yaml

- name: visualiza seu arquivo
  shell: "cat {{ kubernetes_resources_directory }}/nri-monitoring/nri-infraestructure.yaml"
  register: result
- debug: msg="{{ result.stdout_lines }}"