---
# Source: nri-bundle/charts/newrelic-logging/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: nri-monitoring
  name: nri-logging

---
# Source: nri-bundle/charts/newrelic-logging/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nri-logging
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]

---
# Source: nri-bundle/charts/newrelic-logging/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nri-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nri-logging
subjects:
- kind: ServiceAccount
  name: nri-logging
  namespace: nri-monitoring

---
# Source: nri-bundle/charts/newrelic-logging/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  namespace: nri-monitoring
  name: nri-logging-sct
type: Opaque
data:
  license: MWE3YmY3MTdmZTc3Njg5YjU4MGU4N2UzOThiMmY1NGI2NTAyYjZhZA==

---
# Source: nri-bundle/charts/newrelic-logging/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nri-monitoring
  name: nri-logging-cfg
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Log_Level info
        Daemon off
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Parsers_File parsers.conf        

    @INCLUDE input-kubernetes.conf
    @INCLUDE output-newrelic.conf
    @INCLUDE filter-kubernetes.conf

  input-kubernetes.conf: |  
    [INPUT]
        Name tail
        Tag kube.*
        Path /var/log/containers/*.log
        Parser docker
        DB /var/log/flb_kube.db
        Mem_Buf_Limit 7MB
        Skip_Long_Lines On
        Refresh_Interval 10
        
  filter-kubernetes.conf: |
    [FILTER]
        Name           record_modifier
        Match          *
        Record         cluster_name ${CLUSTER_NAME}
    
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_URL https://kubernetes.default.svc.cluster.local:443
        Merge_Log Off
        


  output-newrelic.conf: |
    [OUTPUT]
        Name  newrelic
        Match *
        licenseKey ${LICENSE_KEY}
        endpoint ${ENDPOINT}
  
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

---
# Source: nri-bundle/charts/newrelic-logging/templates/daemonset.yaml

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: nri-monitoring
  name: nri-logging
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nri-logging
  template:
    metadata:
      labels:
        app: nri-logging
    spec:
      serviceAccountName: nri-logging
      hostNetwork: true # This option is a requirement for the Infrastructure Agent to report the proper hostname in New Relic.
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 10
      containers:
        - name: nri-logging
          image: "newrelic/newrelic-fluentbit-output:1.3.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ENDPOINT
              value: "https://log-api.newrelic.com/log/v1"
            - name: SOURCE
              value: "kubernetes"
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: nri-logging-sct
                  key: license
            - name: CLUSTER_NAME
              value: "Main-DMZ-treasury-aks-stg-new"
          command:
            - /fluent-bit/bin/fluent-bit
            - -c
            - /fluent-bit/etc/fluent-bit.conf
            - -e
            - /fluent-bit/bin/out_newrelic.so
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
            - name: var
              mountPath: /var
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi            
      volumes:
        - name: fluent-bit-config
          configMap:
            name: nri-logging-cfg
        - name: var
          hostPath:
            path: /var
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists