---
# Source: nri-bundle/charts/nri-kube-events/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nri-kube-events
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]

---
# Source: nri-bundle/charts/nri-kube-events/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nri-kube-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nri-kube-events
subjects:
- kind: ServiceAccount
  name: nri-kube-events
  namespace: nri-monitoring

---
# Source: nri-bundle/charts/nri-kube-events/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |-
    sinks:
    - name: newRelicInfra
      config:
        agentEndpoint: http://localhost:8001/v1/data
        agentHTTPTimeout: 30s
        clusterName: Main-DMZ-treasury-aks-stg-new

metadata:
  name: nri-kube-events-cfg
  namespace: nri-monitoring

---
# Source: nri-bundle/charts/nri-kube-events/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: nri-kube-events-sct
  namespace: nri-monitoring
type: Opaque
data:
  licenseKey: MWE3YmY3MTdmZTc3Njg5YjU4MGU4N2UzOThiMmY1NGI2NTAyYjZhZA==

---
# Source: nri-bundle/charts/nri-kube-events/templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kube-events
  namespace: nri-monitoring
  labels:
    app: nri-kube-events
    app.kubernetes.io/name: nri-kube-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nri-kube-events
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nri-kube-events
    spec:
      containers:
        - name: kube-events
          image: newrelic/nri-kube-events:1.1.0
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          imagePullPolicy: IfNotPresent
          args: ["-config", "/app/config/config.yaml", "-loglevel", "debug"]
          volumeMounts:
            - name: config-volume
              mountPath: /app/config

        - name: infra-agent
          image: newrelic/k8s-events-forwarder:1.11.24
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            privileged: false
            runAsUser: 1000 # nri-kube-events
            runAsGroup: 2000 # nri-kube-events
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8001
          env:
            - name: NRIA_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: nri-kube-events-sct
                  key: licenseKey
          volumeMounts:
            - mountPath: /var/db/newrelic-infra/data
              name: tmpfs-data
            - mountPath: /var/db/newrelic-infra/user_data
              name: tmpfs-user-data
            - mountPath: /tmp
              name: tmpfs-tmp
      serviceAccountName: nri-kube-events
      volumes:
        - name: config-volume
          configMap:
            name: nri-kube-events-cfg
        - name: tmpfs-data
          emptyDir: {}
        - name: tmpfs-user-data
          emptyDir: {}
        - name: tmpfs-tmp
          emptyDir: {}

---
# Source: nri-bundle/charts/nri-kube-events/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-kube-events
  namespace: nri-monitoring